name: kandy
description: A new Flutter application.

version: 1.0.0+1

environment:
   sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flick_video_player:
  # flutter_widgets: 
  video_player: 
  provider: 
  cloud_firestore: 
  url_launcher: 
  # custom_navigation_drawer:
  carousel_slider:
  bottom_navy_bar: 
  # expandable_card: 
  cupertino_icons: 
  font_awesome_flutter: 
  dio: 
  folding_cell: 
  firebase_auth: 
  firebase_database: 
  cached_network_image: 
  connectivity_widget:
  firebase_messaging: 
  # device_id:
  network_to_file_image:
  # path_provider:
  # carousel_pro:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/Netflix-logo.png
    - images/netflix_icon.png
    - images/launch_image.png
    - images/pro_pic.png
